#!/bin/bash
username=$1
password=$(uuidgen)
mysql_version="$(mysql -V | grep -i mariadb)"
auth_statement=""

if [ "$username" = "" ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

if [ "$password" = "" ]; then
    echo "Error: password is empty. Please install 'uuid-runtime' first."
    exit 1
fi


mariadb -e "CREATE USER '$username' IDENTIFIED $auth_statement BY '$password';"
mariadb -e "CREATE DATABASE $username;"
mariadb -e "GRANT ALL PRIVILEGES ON $username.* TO $username WITH GRANT OPTION;"
mariadb -e "flush privileges;";
mariadb -e "select Host, User, plugin from mysql.user;"

echo "Username: $username"
echo "Password: $password"
