- name: Install Packages
  community.general.pacman:
    name:
      - acme.sh
      - nginx
- name: Install Scripts
  copy:
    src: files/exec/
    dest: /usr/local/bin/
    mode: '0755'
- import_tasks: tasks/acme.yml
- name: Check Certificate Existence
  stat:
    path: "{{ ssl_certificate_path }}/fullchain.pem"
  register: ssl_certificate
- import_tasks: tasks/bootstrap_certificate.yml
  when: ssl_certificate.stat.exists == false
- import_tasks: tasks/nginx.yml
