- name: nginx @ Copy Configurations
  copy:
    src: files/nginx/
    dest: /etc/nginx/
    mode: '0644'
- name: nginx @ Create Directorys
  file:
    state: "{{ item.state | default('directory') }}"
    src: "{{ item.src | default(omit) }}"
    path: "{{ item.path }}"
  with_items:
    - path: /etc/nginx/sites-available
    - path: /etc/nginx/sites-enabled
    - path: /srv/web
    - path: /srv/http
      state: absent
    - path: /srv/ftp
      state: absent
    - path: /etc/nginx/sites-enabled/default.conf
      src: /etc/nginx/sites-available/default.conf
      state: link
- name: nginx @ Systemd
  systemd_service:
    enabled: true
    state: started
    name: nginx
- name: nginx @ Allow UFW Access
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    state: enabled
    comment: "{{ item }}"
  loop:
    - http
    - https
