- hosts: web
  become: true
  vars:
    api_domain: deployapi.webservice.luotianyi.dev
    static_websites:
      - project: blog
        domain: luotianyi.dev
        san: blog.luotianyi.dev
      - project: wiki
        domain: luotianyi.dev
        san: wiki.luotianyi.dev

  tasks:
    # - name: Install DeployKit API ACME Certificates
    #   command: "acme.sh-install-cert-nginx {{ api_domain }}"
    # - name: Deploy DeployKit API NGINX Configuration
    #   vars:
    #     nginx_tls_domain: "{{ api_domain }}"
    #     nginx_server_name: "{{ api_domain }}"
    #     nginx_logger_name: deploykit-api
    #     nginx_upstream: http://10.2.2.2:8000
    #   template:
    #     src: templates/nginx/reverse-proxy.conf.j2
    #     dest: /etc/nginx/sites-available/deploykit-api.conf
    #     owner: root
    #     group: root
    #     mode: '0644'
    # - name: Enable DeployKit API NGINX Configuration
    #   file:
    #     src: /etc/nginx/sites-available/deploykit-api.conf
    #     dest: /etc/nginx/sites-enabled/deploykit-api.conf
    #     state: link
    # - name: Install DeployKit Static Websites ACME Certificates
    #   command: "acme.sh-install-cert-nginx {{ item.domain }}"
    #   with_items: "{{ static_websites }}"
    - name: Deploy DeployKit Static Websites NGINX Configuration
      vars:
        deploykit_project: "{{ item.project }}"
        deploykit_domain: "{{ item.domain }}"
        deploykit_san: "{{ item.san }}"
      template:
        src: templates/nginx/deploykit-static.conf.j2
        dest: /etc/nginx/sites-available/deploykit-static-{{ item.project }}.conf
        owner: root
        group: root
        mode: '0644'
      with_items: "{{ static_websites }}"
    - name: Enable DeployKit Static Websites NGINX Configuration
      file:
        src: "/etc/nginx/sites-available/deploykit-static-{{ item.project }}.conf"
        dest: "/etc/nginx/sites-enabled/deploykit-static-{{ item.project }}.conf"
        state: link
      with_items: "{{ static_websites }}"
