- hosts: web
  vars:
    server_domain: luotianyi.dev
    ssl_certificate_path: "/etc/ssl/private/{{ server_domain }}"
  roles:
    - role: base
      vars:
        ansible_python_interpreter: /usr/bin/python3
        pipx_path: /usr/local/bin/pipx
    - role: docker
    - role: webserver
    - role: portainer
    - role: mysql
