- name: Pull Image
  community.docker.docker_image:
    name: portainer/portainer-ee:latest
    source: pull
- name: Create Volume
  community.docker.docker_volume:
    name: portainer
- name: Start Container
  shell: /usr/local/bin/portainer start
