- name: Install Packages
  community.general.pacman:
    name:
      - acme.sh
- name: Install Scripts
  copy:
    src: files/exec/
    dest: /usr/local/bin/
    mode: '0755'
- name: Setup ACME.sh Certificate Renew Timer
  copy:
    src: files/conf/systemd/
    dest: /etc/systemd/system/
    mode: '0644'
- name: Start ACME.sh Certificate Renew Service
  systemd_service:
    daemon_reload: true
    enabled: true
    state: started
    name: acme-renew-certificate
- name: Enable ACME.sh Certificate Renew Timer
  systemd_service:
    enabled: true
    state: started
    name: acme-renew-certificate.timer
