- name: Setup portainer @ Pull
  community.docker.docker_image:
    name: portainer/portainer-ee:latest
    source: pull
- name: Setup portainer @ Volume
  community.docker.docker_volume:
    name: portainer
- name: Setup portainer @ Start
  shell: /usr/local/bin/portainer start
- name: Setup portainer @ Nginx (Setup)
  template:
    src: templates/nginx/reverse-proxy.conf.j2
    dest: /etc/nginx/sites-available/docker.conf
    mode: '0644'
  vars:
    nginx_server_name: docker.{{ server_domain }}
    nginx_tls_domain: "{{ server_domain }}"
    nginx_logger_name: docker
    nginx_upstream: https://127.0.0.1:9443
- name: Setup portainer @ Nginx (Activate)
  file:
    src: /etc/nginx/sites-available/docker.conf
    dest: /etc/nginx/sites-enabled/docker.conf
    state: link
- name: Setup portainer @ Nginx (Restart)
  systemd_service:
    name: nginx
    state: restarted
