- name: "Create WireGuard Configuration: systemd netdev unit file @ peer -> {{ peer_servername }}"
  template:
    src: templates/systemd-networkd/wireguard.netdev.j2
    dest: /etc/systemd/network/{{ 20 + (peer_network_id | int) }}-wireguard-peer-{{ peer_servername }}.netdev
    mode: '0644'
- name: "Create WireGuard Configuration: systemd network unit file @ peer -> {{ peer_servername }}"
  template:
    src: templates/systemd-networkd/wireguard.network.j2
    dest: /etc/systemd/network/{{ 20 + (peer_network_id | int) }}-wireguard-peer-{{ peer_servername }}.network
    mode: '0644'
